#!/bin/sh
#

function perc() {
    upower -i "$1" | grep 'percentage:' | cut -f 2 -d':' | tr -d '%[:space:]'
}

function stat() {
    upower -i "$1" | grep 'online:' | cut -f 2 -d':' | tr -d '[:space:]'
}

bat1=$(perc /org/freedesktop/UPower/devices/battery_BAT0)
bat2=$(perc /org/freedesktop/UPower/devices/battery_BAT1)

state=$(stat /org/freedesktop/UPower/devices/line_power_AC)

if [ "$1" == "-q" ]; then
    sym="🔌"
    if [ "$state" == "no" ]; then
        sym="🔋"
    fi
    pc=$(echo "($bat1 + $bat2) / 2" | bc)
    if [ $pc -lt 100 ]; then
        echo "${sym}${pc}%"
    else
        echo $sym
    fi
else
    echo "BAT0 $bat1%  $bat2% BAT1"
fi
