#!/usr/bin/env bash
#
# Blink LEDs
#

CONTROL=~/.carry-on-blinken

if [ $# -gt 0 ]; then
	case $1 in
		start)
			touch $CONTROL
			$0&
			;;
		stop)
			rm $CONTROL
			;;
	esac
else
	while [ -f $CONTROL ]; do
		xset dpms led 3
		sleep 1
		xset dpms -led 3
		sleep 1
	done
fi
