#!/bin/bash

PID=$(pgrep offlineimap)

[[ -n "$PID" ]] && kill $PID

if [ -f ~/.newvars ]; then
	source ~/.newvars
fi

if ping -c 1 -w 5 google.com 1>/dev/null 2>&1; then
	offlineimap -q -o -u quiet &
fi
