#!/bin/sh

# sync with imap and update index
mbsync -a
mu index --quiet

#mu find maildir:/gmail/INBOX AND flag:new AND list:akka-user.googlegroups.com --exec='rm'
#mu find maildir:/gmail/INBOX AND flag:new AND list:scala-user.googlegroups.com --exec='rm'
#mu find maildir:/gmail/INBOX AND flag:new AND list:scala-user.googlegroups.com --exec='rm'
#mu find maildir:/gmail/INBOX AND flag:new AND list:arch-general.archlinux.org --exec='rm'
#
## update index to reflect any moved mail and sync
#mu index --quiet
#mbsync -a
